/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class umeng_com_jnitech_JniInterface */

#ifndef _Included_umeng_com_jnitech_JniInterface
#define _Included_umeng_com_jnitech_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     umeng_com_jnitech_JniInterface
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_umeng_com_jnitech_JniInterface_sayHello
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_umeng_com_jnitech_JniInterface_test
        (JNIEnv *, jclass);
JNIEXPORT jstring JNICALL Java_umeng_com_jnitech_JniInterface_callJavaString
        (JNIEnv *, jclass);
JNIEXPORT jstring JNICALL Java_umeng_com_jnitech_JniInterface_callJavaStringSum
        (JNIEnv *, jclass,jstring,jstring);
JNIEXPORT jstring JNICALL Java_umeng_com_jnitech_JniInterface_callNonStaticJavaString
        (JNIEnv *, jclass);
JNIEXPORT jstring JNICALL Java_umeng_com_jnitech_JniInterface_sum
        (JNIEnv *, jclass,jint,jint);
JNIEXPORT jstring JNICALL Java_umeng_com_jnitech_JniInterface_sumCallBack
        (JNIEnv *, jclass,jint,jint);
JNIEXPORT jstring JNICALL Java_umeng_com_jnitech_JniInterface_testArray
        (JNIEnv *, jclass,jobjectArray,jobjectArray);
#ifdef __cplusplus
}

#endif
#endif
